// REDUX ACTION TYPES
export const TICK = 'TICK'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'

export const INIT = 'INIT'

export const INVALIDATE_PAGE = 'INVALIDATE_PAGE'
export const INVALIDATE_LOCATIONS = 'INVALIDATE_PAGE'
export const INVALIDATE_EPISODES = 'INVALIDATE_PAGE'

export const REQUEST_PAGE = 'REQUEST_PAGE'
export const REQUEST_EPISODES = 'REQUEST_EPISODES'
export const REQUEST_LOCATIONS = 'REQUEST_LOCATIONS'

export const RECEIVE_PAGE = 'RECEIVE_PAGE'
export const RECEIVE_EPISODES = 'RECEIVE_EPISODES'
export const RECEIVE_LOCATIONS = 'RECEIVE_LOCATIONS'

export const DIALOG_INFO = 'DIALOG_INFO'
export const DIALOG_LOCATIONS = 'DIALOG_LOCATIONS'
export const DIALOG_EPISODES = 'DIALOG_EPISODES'

export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

export const PAGE_CHANGE = 'PAGE_CHANGE'
export const PRELOAD_NEXT_PAGE = 'PRELOAD_NEXT_PAGE'
export const PRELOAD_PREV_PAGE = 'PRELOAD_PREV_PAGE'
